name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Who Did It
        id: whoDidIt
        run: echo "::set-output name=userName::SAMSMITHNZ"
      - run: echo 'Actor is [${{ steps.whoDidIt.outputs.userName }}]'
      - run: printenv 
      - run: printenv ABC123
